version: "3.8"

volumes: 
    SmartSchoolDb:

networks: 
    mysqlNET:
    smartschoolNET:

services: 

    mysql:
        image: "mysql:5.7"
        container_name: mysql
        networks: 
            - mysqlNET
        ports: 
            - "3306:3306"
        volumes: 
            - SmartSchoolDb:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=root123
            - MYSQL_ROOT_HOST=%
            - bind-adress:0.0.0.0
    
    smartschool:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: smartschool
        networks: 
            - mysqlNET
            - smartschoolNET
        ports: 
            - 5000:80
        environment: 
            - DBHOST=mysql
        depends_on: 
            - mysql